repo_processor:
  chunksize: 1000
  do_gzip: true
pydriller_kwargs:
  only_no_merge: true
num_workers: 4
org_repo_sep: "#"
paths:
  temp_clone_dir: ../temp
  input_dir: ../repos
  output_dir: ../extracted_data_jsonl