training_processor:
  diff_tokenizer_name_or_path: ../../tokenizer/diff_tokenizer.json
  msg_tokenizer_name_or_path: distilgpt2
  diff_kwargs:
    truncation: true
    max_length: 500
    return_attention_mask: false
  msg_kwargs:
    truncation: true
    return_attention_mask: false
paths:
  input_root_dir: ../../extracted_data
  output_root_dir: ../../processed_data