training_processor:
  blocksize: 1e8
  chunksize: 5000
  clean_temp_files: true
  msg_tokenizer_name: distilgpt2
  diff_kwargs:
    truncation: true
    max_length: 500
    return_attention_mask: false
  msg_kwargs:
    truncation: true
    return_attention_mask: false
paths:
  diff_tokenizer_path: tokenizer/diff_tokenizer.json
  input_dir: extracted_data_jsonl
  output_dir: processed_data