tokenizer:
  _target_: tokenizers.models.BPE
  dropout: 0.5
  unk_token: '[UNK]'
pre_tokenizer:
  _target_: tokenizers.pre_tokenizers.ByteLevel
  add_prefix_space: false
trainer:
  _convert_: partial
  _target_: tokenizers.trainers.BpeTrainer
  special_tokens: ['[UNK]', '[CLS]', '[SEP]', '[PAD]', '[MASK]']
paths:
  data_root_dir: ../../extracted_data/diffs/
  tokenizer_root_dir: ../../tokenizer/diff_tokenizer.json