data_format: jsonl
clones_ready: true

author_processor:
  chunksize: 256

outliers_processor:
  chunksize: 256
  n_workers: 4
  lower_percentile: 0.01
  upper_percentile: 0.95

pre_deduplication_processor:
  chunksize: 1000
  n_workers: 8

post_deduplication_processor:
  chunksize: 1000
  n_workers: 8

message_processor:
  chunksize: 1000
  n_workers: 8

diff_processor:
  chunksize: 2000
  n_workers: 16

paths:
  input_dir: test/extracted_data_jsonl
  percentile_dir: test/percentiles
  deduplication_dir: test/deduplication
