data_format: jsonl
n_workers: 4

parts:
  - train
  - val
  - test

repo_processor:
  chunksize: 25
  max_lines: 10000

pydriller_kwargs:
  only_no_merge: true
  skip_whitespaces: true
  since: 01-01-2017

paths:
  temp_clone_dir: temp
  input_dir: artifacts
  output_dir: extracted_data_jsonl
