data_format: jsonl
line_sep: "\n"

parts:
  - train
  - val
  - test

outliers_processor:
  args:
    chunksize: 64
    n_workers: 4
  lower_percentile: 5
  upper_percentile: 95

message_processor:
  args:
    chunksize: 16000
    n_workers: 4
  replace_patterns: false

diff_processor:
  args:
    chunksize: 16000
    n_workers: 4

pre_deduplication_processor:
  args:
    chunksize: 1000
    n_workers: 4

exact_hash_processor:
  args:
    chunksize: 10000
    n_workers: 4
  use_tokens_hash: false
  use_cache: false

post_deduplication_processor:
  args:
    chunksize: 16000
    n_workers: 1
  only_full_inner_clones: false
  only_train_inner_clones: false
  only_train_outer_clones: true
  identical_clones: true

metadata_processor:
  args:
    chunksize: 16000
    n_workers: 1

paths:
  input_dir: extracted_data_jsonl
  stats_percentile_dir: n_tokens
  deduplication_dir: deduplication
  metadata_dir: metadata
