data_format: jsonl

training_processor:
  chunksize: 1000
  clean_temp_files: false
  diff_tokenizer_name_or_path: tokenizer/diff_tokenizer.json
  msg_tokenizer_name_or_path: distilgpt2
  diff_kwargs:
    truncation: false
    return_attention_mask: false
  msg_kwargs:
    truncation: false
    return_attention_mask: false

paths:
  input_dir: extracted_data_jsonl
  output_dir: processed_data