data_format: jsonl

diff_extractor:
  chunksize: 32000
  upper_percentile: 0.9
  n_workers: 16

tokenizer:
  _target_: tokenizers.models.BPE
  dropout: 0.5
  unk_token: '[UNK]'

trainer:
  _convert_: all
  _target_: tokenizers.trainers.BpeTrainer
  special_tokens: ['[UNK]', '[CLS]', '[SEP]', '[PAD]', '[MASK]', '\n']

paths:
  input_dir: extracted_data_jsonl
  tokenizer_dir: tokenizer