data_format: jsonl
n_workers: 4
org_repo_sep: "#"

repo_processor:
  chunksize: 1000

pydriller_kwargs:
  only_no_merge: true
  skip_whitespaces: true

paths:
  temp_clone_dir: test/temp
  input_dir: test/repos
  output_dir: test/extracted_data_jsonl
